# local_backend: true
site_url: https://stefanpuia.co.uk

backend:
  name: git-gateway
  branch: main

media_folder: /uploads
public_folder: /uploads
locale: en
# publish_mode: editorial_workflow

collections:
  - name: global-config
    label: Global configuration
    extension: json
    create: false
    delete: false
    slug: "{{slug}}"
    files:
      - label: Home page
        name: config-home
        file: src/_data/config/home.json
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: index.njk

          - label: Hero header
            name: heroHeader
            widget: string
            hint: "HTML content"

          - label: Hero description
            name: heroDescription
            widget: text
            hint: "HTML content"

          - label: Blog button
            name: blogButton
            widget: string

          - label: Portfolio button
            name: portfolioButton
            widget: string

          - label: Featured
            name: featured
            widget: object
            fields:
              - label: Header
                name: header
                widget: string

      - label: Header
        name: config-header
        file: src/_data/config/header.json
        fields:
          - label: Overlay
            name: overlay
            widget: image
            required: false

          - label: Background Image
            name: background
            widget: image
            required: false

          - label: Avatar
            name: avatar
            widget: image

          - label: Avatar alt
            name: avatarAlt
            widget: string
            required: false

          - label: Description
            name: description
            widget: text
            hint: HTML content

          - label: Footer Overlay
            name: footerOverlay
            widget: image
            required: false

          - label: Footer Background Image
            name: footerBackground
            widget: image
            required: false

      - label: Errors
        name: config-errors
        file: src/_data/config/errors.json
        fields:
          - label: 404 Error
            name: http_404
            widget: object
            fields:
              - label: Header text
                name: header
                widget: markdown

      - label: Acknowledgements
        name: acknowledgements
        file: src/_data/config/acknowledgements.json
        fields:
          - label: Content
            name: body
            widget: markdown

  - label: Technologies
    name: technologies
    folder: src/technologies
    label_singular: Technology
    create: true
    slug: "{{key}}"
    summary: '{{fields.description}}'
    fields:
      - label: Key
        name: key
        widget: string
        required: true
      - label: Description
        name: description
        widget: string
        required: true
      - label: Image
        name: image
        widget: image
        required: true
        hint: image urls, each on a new line https://devicon.dev/

  - name: blog
    label: Blog
    folder: src/blog
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string

      - label: Full Image
        name: imageFull
        widget: image
        required: false

      - label: Image alt
        name: imageAlt
        widget: string
        required: false

      - label: Image credit
        name: imageCredit
        widget: string
        required: false

      - label: Content
        name: body
        widget: markdown
        required: false

      - label: Portfolio
        name: portfolio
        widget: object
        fields:
          - label: Is portfolio
            name: isPortfolio
            widget: boolean
            default: false

          - label: GitHub Source
            name: githubSource
            widget: string
            required: false

          - label: Live URL
            name: liveUrl
            widget: string
            required: false

          - label: Technologies
            name: technologies
            widget: relation
            collection: "technologies"
            value_field: "key"
            search_fields: ["key", "description"]
            display_fields: ["description"]
            multiple: true
            required: false

      - label: Featured
        name: featured
        widget: object
        fields:
          - label: Is featured?
            name: isFeatured
            widget: boolean
            default: false

          - label: Description
            name: description
            widget: text
            required: false

          - label: Image thumbnail
            name: imageThumb
            widget: image
            required: false
            hint: works best with 2:1
